# Site settings
title: Zhiping Luo
email: luozhipi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  techniques of interest, graphics and animation research, github projects.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  luozhipi

# Build settings
markdown: kramdown
